import type { SxProps, Theme } from '@mui/material';

export const productPageStyles: Record<string, SxProps<Theme>> = {
  root: {
    display: 'flex',
    justifyContent: 'center',
    height: '100%',
    overflow: 'hidden',
    gap: 3,
    bgcolor: 'background.default',
  },
  imageSection: {
    flex: '0 0 auto',
    overflow: 'hidden',
  },
  image: {
    width: '850px',
    height: '850px',
    objectFit: 'cover',
    display: 'block',
    flexShrink: 0,
  },
  imagePlaceholder: {
    width: '850px',
    height: '850px',
    flexShrink: 0,
    bgcolor: 'grey.100',
  },
  infoSection: {
    flex: '0 0 33%',
    px: 6,
    py: 8,
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    overflowY: 'auto',
  },
  name: {
    fontSize: '1.1rem',
    fontWeight: 400,
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
    color: 'text.primary',
  },
  price: {
    fontSize: '0.95rem',
    color: 'text.primary',
    mb: 1,
  },
  addToCartButton: {
    width: '100%',
    border: '1px solid',
    borderColor: 'text.primary',
    borderRadius: 0,
    color: 'text.primary',
    bgcolor: 'transparent',
    py: 1.5,
    fontSize: '0.8rem',
    letterSpacing: '0.1em',
    fontWeight: 400,
    '&:hover': {
      bgcolor: 'text.primary',
      color: 'background.default',
    },
  },
  buttonContent: {
    position: 'relative',
    width: '100%',
    height: '24px',
  },
  buttonStateDefault: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 1,
    opacity: 1,
    transition: 'opacity 0.25s ease',
    '.is-added &': { opacity: 0 },
  },
  buttonStateAdded: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 1,
    opacity: 0,
    transition: 'opacity 0.25s ease',
    '.is-added &': { opacity: 1 },
  },
  description: {
    mt: 2,
    fontSize: '0.9rem',
    color: 'text.primary',
    lineHeight: 1.7,
    '& strong': { fontWeight: 600 },
    '& em': { fontStyle: 'italic' },
    '& p': { mb: 1 },
  },
};
